DROP TABLE `item` IF EXISTS;
CREATE TABLE `item` (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(128) NOT NULL,
	description TEXT NOT NULL,
	category VARCHAR(64) NOT NULL,
	price DECIMAL(8,2) NOT NULL,
	name VARCHAR(128) NOT NULL,
	latitude DECIMAL(9,6) NOT NULL,
	longitude DECIMAL(9,6) NOT NULL,
	status VARCHAR(64) NOT NULL,
	create_date	INT(10) UNSIGNED NOT NULL
);